version: '3.9'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - /var/www/html:/var/www/html:ro
    - ./docker/production/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
    - jenkins
  jenkins:
    build:
      context: docker/common/jenkins
    volumes:
    - jenkins-data:/var/jenkins_home
    - docker-certs:/certs/client:ro
    depends_on:
    - docker
    environment:
      DOCKER_HOST: tcp://2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1

  docker:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERDIR: /certs
    volumes:
    - jenkins-data:/var/jenkins_home
    - docker-certs:/certs/client
    - docker-data:/var/lib/docker

volumes:
  jenkins-data:
  docker-certs:
  docker-data:
