---
# TODO this task doesn't work and I don't know why
#- name: Add OpenJDK repository
#  apt_repository:
#    repo: 'deb http://ftp.us.debian.org/debian sid main'
#    state: present
#    filename: openjdk
#    update_cache: yes

- name: Install OpenJDK
  apt:
    name:
      - openjdk-8-jre-headless
    state: present
    update_cache: yes
