---
- name: Set Up Manager
  hosts: manager
  remote_user: root
  roles:
    - swap
    - docker
    - certbot
    - jenkins
- name: Set Up Agent
  hosts: agent
  remote_user: root
  roles:
    - swap
    - docker
    - java
    - agent
